<Layout>:
    orientation: 'vertical'
    spacing: 20

    BoxLayout:
        size_hint_y: None
        height: 50
        Label:
            text: 'Welcome image recognation'
            size_hint_x: .9
            bold: True

        Button:
            text: 'x'
            size_hint_x: .1
    BoxLayout:
        orientation:'vertical'
        TextInput:
            hint_text: 'username'
        TextInput:
            hint_text:'password'
    Button:
        text: 'Login'
        
        